#!/usr/bin/env python3

"""
===========================================================================
Lighthouse Technology
Detection Metrics Generator

Domain 5
Phase G – Detection Engineering & Coverage Measurement

Purpose:
    Generate enterprise detection engineering metrics from
    normalized validation results.

Author:
    Lighthouse Technology Detection Engineering Team

Version:
    1.0
===========================================================================
"""

import csv
from pathlib import Path
from datetime import datetime

INPUT_FILE = Path(
    "data/normalized/detection/LHT-DetectionValidationResults.csv"
)

OUTPUT_FILE = Path(
    "reports/detection/Detection-Metrics-Report.md"
)


def load_validation_results():

    if not INPUT_FILE.exists():

        print(f"[ERROR] Validation results not found:\n{INPUT_FILE}")
        return []

    results = []

    with open(INPUT_FILE, newline="", encoding="utf-8") as csvfile:

        reader = csv.DictReader(csvfile)

        for row in reader:

            results.append(row)

    return results


def calculate_metrics(results):

    total = len(results)

    passed = sum(
        1
        for r in results
        if r["Simulation_Result"] == "PASS"
    )

    tuning = sum(
        1
        for r in results
        if r["Simulation_Result"] == "TUNING_REQUIRED"
    )

    failed = sum(
        1
        for r in results
        if r["Simulation_Result"] == "FAIL"
    )

    success_rate = 0

    if total > 0:

        success_rate = round((passed / total) * 100, 2)

    return {

        "total": total,
        "passed": passed,
        "tuning": tuning,
        "failed": failed,
        "success_rate": success_rate

    }


def generate_report(metrics):

    OUTPUT_FILE.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with open(
        OUTPUT_FILE,
        "w",
        encoding="utf-8"
    ) as report:

        report.write("# Detection Metrics Report\n\n")

        report.write(
            f"Generated: "
            f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        )

        report.write("## Executive Summary\n\n")

        report.write(
            f"- Total Detection Simulations: "
            f"**{metrics['total']}**\n"
        )

        report.write(
            f"- Successful Validations: "
            f"**{metrics['passed']}**\n"
        )

        report.write(
            f"- Tuning Required: "
            f"**{metrics['tuning']}**\n"
        )

        report.write(
            f"- Failed Validations: "
            f"**{metrics['failed']}**\n"
        )

        report.write(
            f"- Detection Success Rate: "
            f"**{metrics['success_rate']}%**\n\n"
        )

        report.write("---\n\n")

        report.write("## Business Impact\n\n")

        report.write(
            "These metrics provide executive visibility into "
            "enterprise detection effectiveness and identify "
            "areas requiring additional tuning before "
            "production deployment.\n\n"
        )

        report.write("---\n\n")

        report.write(
            "*Automatically generated by the Lighthouse "
            "Technology Detection Metrics Generator.*\n"
        )


def print_summary(metrics):

    print("=" * 70)
    print(" Lighthouse Technology Detection Metrics Generator")
    print("=" * 70)

    print()

    print(f"Total Simulations      : {metrics['total']}")
    print(f"Successful             : {metrics['passed']}")
    print(f"Tuning Required        : {metrics['tuning']}")
    print(f"Failed                 : {metrics['failed']}")
    print(f"Success Rate           : {metrics['success_rate']}%")

    print("\nReport Generated:")

    print(f"  {OUTPUT_FILE}")

    print("\nMetrics Generation Complete.")


def main():

    results = load_validation_results()

    if not results:

        print("[WARNING] No validation results available.")
        return

    metrics = calculate_metrics(results)

    generate_report(metrics)

    print_summary(metrics)


if __name__ == "__main__":
    main()
